// ─── Category Config ────────────────────────────────────────────────────────
export const CATS = {
  1:    { label: 'Salt',                 color: '#FFFFFF' },
  2:    { label: 'Sweet',                color: '#F8BBD0' },
  3:    { label: 'Kharas',               color: '#8D6E63' },
  4:    { label: 'Tarkari / Curry',      color: '#F4A261' },
  5:    { label: 'Roti',                 color: '#F5DEB3' },
  '6a': { label: 'Main Course - Rice',   color: '#BDBDBD' },
  '6b': { label: 'Main Course - Gravy',  color: '#FFD54F' },
  7:    { label: 'Salad / Pickle',       color: '#388E3C' },
  8:    { label: 'Fruit',                color: '#7B1FA2' },
  9:    { label: 'Drink',                color: '#1565C0' },
};

// ─── Menu Database ───────────────────────────────────────────────────────────
// name: '' means item is not served that meal
export const MEALS = [
  { id: 'n1', title: 'Night 1 — Dinner', sub: 'Muharram 1', items: [
    { cat: 1,    name: 'Salt',                                  serving: '' },
    { cat: 2,    name: 'Ice Cream',                             serving: '' },
    { cat: 3,    name: 'Chana Bateta (Chickpea & Potato)',      serving: '' },
    { cat: 4,    name: 'Red Meat Curry',                        serving: 'Serve with Roti or Rice' },
    { cat: 5,    name: 'Roti / Manda / Naan',                   serving: '' },
    { cat: '6a', name: 'Dal Chawal (Lentil Rice)',               serving: '' },
    { cat: '6b', name: 'Palidu (Gravy)',                         serving: 'Serve with Rice' },
    { cat: 7,    name: 'Mixed Pickle — Mango & Lime',           serving: '' },
    { cat: 8,    name: 'Uncut Whole Fruit',                      serving: '' },
    { cat: 9,    name: 'Fresh Fruit Juice',                      serving: '' },
  ]},
  { id: 'd1', title: 'Day 1 — Lunch', sub: 'Muharram 1', items: [
    { cat: 1,    name: 'Salt',                                  serving: '' },
    { cat: 2,    name: 'Ice Cream',                             serving: '' },
    { cat: 3,    name: '',                                      serving: '' },
    { cat: 4,    name: 'Potato & Meat Curry',                   serving: 'Serve with Roti or Rice' },
    { cat: 5,    name: 'Roti / Manda / Naan',                   serving: '' },
    { cat: '6a', name: 'Plain Rice',                            serving: '' },
    { cat: '6b', name: '',                                      serving: '' },
    { cat: 7,    name: 'Pickle (Achar)',                        serving: '' },
    { cat: 8,    name: 'Uncut Whole Fruit',                      serving: '' },
    { cat: 9,    name: 'Juice / Sharbat',                       serving: '' },
  ]},
  { id: 'n2', title: 'Night 2 — Dinner', sub: 'Muharram 2', items: [
    { cat: 1,    name: 'Salt',                                  serving: '' },
    { cat: 2,    name: 'Halwa (Sweet Pudding)',                  serving: '' },
    { cat: 3,    name: 'Local Kharas (Vegetable or Meat)',      serving: '' },
    { cat: 4,    name: '',                                      serving: '' },
    { cat: 5,    name: 'Roti / Manda / Naan',                   serving: '' },
    { cat: '6a', name: 'Plain Rice',                            serving: '' },
    { cat: '6b', name: 'Dal Gosht (Lentil Meat Gravy)',         serving: 'Serve with Rice' },
    { cat: 7,    name: 'Pickle (Achar)',                        serving: '' },
    { cat: 8,    name: 'Uncut Whole Fruit',                      serving: '' },
    { cat: 9,    name: 'Fresh Fruit Juice',                      serving: '' },
  ]},
  { id: 'd2', title: 'Day 2 — Lunch', sub: 'Muharram 2', items: [
    { cat: 1,    name: 'Salt',                                  serving: '' },
    { cat: 2,    name: 'Ice Cream',                             serving: '' },
    { cat: 3,    name: 'Veg Noodles (Live)',                    serving: '' },
    { cat: 4,    name: 'Nihari (Slow-Cooked Meat Stew)',        serving: 'Serve with Roti' },
    { cat: 5,    name: 'Roti / Manda / Naan',                   serving: '' },
    { cat: '6a', name: 'Tempered Red Lentil Khichdi',           serving: '' },
    { cat: '6b', name: '',                                      serving: '' },
    { cat: 7,    name: 'Pickle (Achar)',                        serving: '' },
    { cat: 8,    name: 'Uncut Whole Fruit',                      serving: '' },
    { cat: 9,    name: 'Honey Water',                           serving: '' },
  ]},
  { id: 'n3', title: 'Night 3 — Dinner', sub: 'Muharram 3', items: [
    { cat: 1,    name: 'Salt',                                  serving: '' },
    { cat: 2,    name: 'Maleeda (Sweet Bread Pudding)',         serving: '' },
    { cat: 3,    name: 'Dahi Vada (Lentil Dumplings in Yogurt)', serving: '' },
    { cat: 4,    name: 'Kazi & Meat Curry',                     serving: 'Serve with Roti or Rice' },
    { cat: 5,    name: 'Roti / Manda / Naan',                   serving: '' },
    { cat: '6a', name: 'Plain Rice',                            serving: '' },
    { cat: '6b', name: '',                                      serving: '' },
    { cat: 7,    name: 'Lemon Pickle',                          serving: '' },
    { cat: 8,    name: 'Uncut Whole Fruit',                      serving: '' },
    { cat: 9,    name: 'Fresh Fruit Juice',                      serving: '' },
  ]},
  { id: 'd3', title: 'Day 3 — Lunch', sub: 'Muharram 3', items: [
    { cat: 1,    name: 'Salt',                                  serving: '' },
    { cat: 2,    name: 'Ice Cream',                             serving: '' },
    { cat: 3,    name: 'Haneeth / Spiced Meat (Starter)',       serving: '' },
    { cat: 4,    name: '',                                      serving: '' },
    { cat: 5,    name: 'Breadsticks with Cheese Dip',           serving: '' },
    { cat: '6a', name: 'Hasha with Meat',                       serving: '' },
    { cat: '6b', name: '',                                      serving: '' },
    { cat: 7,    name: 'Green Salad with Honey Mustard Dressing', serving: '' },
    { cat: 8,    name: 'Uncut Whole Fruit',                      serving: '' },
    { cat: 9,    name: 'Rose Syrup Drink',                      serving: '' },
  ]},
  { id: 'n4', title: 'Night 4 — Dinner', sub: 'Muharram 4', items: [
    { cat: 1,    name: 'Salt',                                  serving: '' },
    { cat: 2,    name: 'Carrot Halwa / Dry Fruit Halwa',        serving: '' },
    { cat: 3,    name: 'Local Kharas (Vegetable or Meat)',      serving: '' },
    { cat: 4,    name: 'Whole Red Lentil Meat Curry',           serving: 'Serve with Roti or Rice' },
    { cat: 5,    name: 'Roti / Manda / Naan',                   serving: '' },
    { cat: '6a', name: 'Plain Rice',                            serving: '' },
    { cat: '6b', name: '',                                      serving: '' },
    { cat: 7,    name: 'Yogurt with Cornflakes',                serving: '' },
    { cat: 8,    name: 'Uncut Whole Fruit',                      serving: '' },
    { cat: 9,    name: 'Fresh Fruit Juice',                      serving: '' },
  ]},
  { id: 'd4', title: 'Day 4 — Lunch', sub: 'Muharram 4', items: [
    { cat: 1,    name: 'Salt',                                  serving: '' },
    { cat: 2,    name: 'Ice Cream',                             serving: '' },
    { cat: 3,    name: 'Kachumber (Cucumber Salad)',            serving: '' },
    { cat: 4,    name: '',                                      serving: '' },
    { cat: 5,    name: 'Roti / Manda / Naan',                   serving: '' },
    { cat: '6a', name: 'Meat & Red Lentil Pilaf',               serving: '' },
    { cat: '6b', name: 'Kadhi (Yogurt Curry)',                   serving: 'Serve with Rice' },
    { cat: 7,    name: 'Shafout (Flatbread with Yogurt)',       serving: '' },
    { cat: 8,    name: 'Uncut Whole Fruit',                      serving: '' },
    { cat: 9,    name: 'Rose Water',                            serving: '' },
  ]},
  { id: 'n5', title: 'Night 5 — Dinner', sub: 'Muharram 5', items: [
    { cat: 1,    name: 'Salt',                                  serving: '' },
    { cat: 2,    name: 'Local Sweet Dish',                      serving: '' },
    { cat: 3,    name: 'Daba Gosht (Slow-Cooked Pot Meat)',     serving: '' },
    { cat: 4,    name: '',                                      serving: '' },
    { cat: 5,    name: 'Roti / Garlic Bread / Naan',            serving: '' },
    { cat: '6a', name: 'Steamed Rice with Banana',              serving: '' },
    { cat: '6b', name: 'Veg Sweet & Sour Gravy',                serving: 'Serve with Rice' },
    { cat: 7,    name: 'Yogurt Boondi Salad',                   serving: '' },
    { cat: 8,    name: 'Uncut Whole Fruit',                      serving: '' },
    { cat: 9,    name: 'Fresh Fruit Juice',                      serving: '' },
  ]},
  { id: 'd5', title: 'Day 5 — Lunch', sub: 'Muharram 5', items: [
    { cat: 1,    name: 'Salt',                                  serving: '' },
    { cat: 2,    name: 'Ice Cream',                             serving: '' },
    { cat: 3,    name: '',                                      serving: '' },
    { cat: 4,    name: 'Palak Bhaji Live (Spinach Stir Fry)',   serving: 'Serve with Roti' },
    { cat: 5,    name: 'Roti / Manda / Naan',                   serving: '' },
    { cat: '6a', name: 'White Meat Biryani',                    serving: '' },
    { cat: '6b', name: 'Mamho / Chamas',                        serving: 'Serve with Biryani' },
    { cat: 7,    name: 'Chickpea & Cucumber Salad',             serving: '' },
    { cat: 8,    name: 'Uncut Whole Fruit',                      serving: '' },
    { cat: 9,    name: '',                                      serving: '' },
  ]},
  { id: 'n6', title: 'Night 6 — Dinner', sub: 'Muharram 6', items: [
    { cat: 1,    name: 'Salt',                                  serving: '' },
    { cat: 2,    name: 'Sholo (Sweet Saffron Rice)',            serving: '' },
    { cat: 3,    name: 'Cream Pasta',                           serving: '' },
    { cat: 4,    name: '',                                      serving: '' },
    { cat: 5,    name: 'Manda / Baguette',                      serving: '' },
    { cat: '6a', name: 'Khichdi',                               serving: '' },
    { cat: '6b', name: 'Khurdi (Light Broth)',                   serving: 'Serve with Khichdi' },
    { cat: 7,    name: 'Cream & Cheese with Baguette',          serving: '' },
    { cat: 8,    name: 'Uncut Whole Fruit',                      serving: '' },
    { cat: 9,    name: 'Fresh Fruit Juice',                      serving: '' },
  ]},
  { id: 'd6', title: 'Day 6 — Lunch', sub: 'Muharram 6', items: [
    { cat: 1,    name: 'Salt',                                  serving: '' },
    { cat: 2,    name: 'Maleeda (Sweet Bread Pudding)',         serving: '' },
    { cat: 3,    name: 'Black Pepper Butter Meat',              serving: '' },
    { cat: 4,    name: '',                                      serving: '' },
    { cat: 5,    name: '',                                      serving: '' },
    { cat: '6a', name: 'Red Lentil Meat Hasha',                 serving: '' },
    { cat: '6b', name: '',                                      serving: '' },
    { cat: 7,    name: 'Lebanese Fattoush / Banana Cucumber Salad', serving: '' },
    { cat: 8,    name: 'Uncut Whole Fruit',                      serving: '' },
    { cat: 9,    name: 'Yogurt (Packed)',                       serving: '' },
  ]},
  { id: 'n7', title: 'Night 7 — Dinner', sub: 'Muharram 7', items: [
    { cat: 1,    name: 'Salt',                                  serving: '' },
    { cat: 2,    name: 'Ice Cream',                             serving: '' },
    { cat: 3,    name: '',                                      serving: '' },
    { cat: 4,    name: 'Pav Bhaji',                             serving: 'Serve with Pav' },
    { cat: 5,    name: 'Pav (Dinner Rolls)',                    serving: '' },
    { cat: '6a', name: 'Akhni Pilaf',                           serving: '' },
    { cat: '6b', name: 'Spinach Soup (Palak Soup)',              serving: 'Serve with Akhni' },
    { cat: 7,    name: 'Pickle (Achar)',                        serving: '' },
    { cat: 8,    name: 'Uncut Whole Fruit',                      serving: '' },
    { cat: 9,    name: 'Fresh Fruit Juice',                      serving: '' },
  ]},
  { id: 'd7', title: 'Day 7 — Lunch', sub: 'Muharram 7', items: [
    { cat: 1,    name: 'Salt',                                  serving: '' },
    { cat: 2,    name: 'Ice Cream',                             serving: '' },
    { cat: 3,    name: '',                                      serving: '' },
    { cat: 4,    name: 'Seasonal Vegetable Curry',              serving: 'Serve with Roti or Rice' },
    { cat: 5,    name: 'Roti / Manda / Naan',                   serving: '' },
    { cat: '6a', name: 'Meat Biryani',                          serving: '' },
    { cat: '6b', name: 'Mamho',                                 serving: 'Serve with Biryani' },
    { cat: 7,    name: 'Spinach Salad with Olive & Crispy Spinach', serving: '' },
    { cat: 8,    name: 'Uncut Whole Fruit',                      serving: '' },
    { cat: 9,    name: '',                                      serving: '' },
  ]},
  { id: 'n8', title: 'Night 8 — Dinner', sub: 'Muharram 8', items: [
    { cat: 1,    name: 'Salt',                                  serving: '' },
    { cat: 2,    name: 'Shahi Nakza (Royal Sweet Dish)',        serving: '' },
    { cat: 3,    name: 'Sukho Gosht (Dry Spiced Meat)',         serving: '' },
    { cat: 4,    name: 'Potato & Methi Curry with Gravy',       serving: 'Serve with Roti or Rice' },
    { cat: 5,    name: 'Roti / Manda / Naan',                   serving: '' },
    { cat: '6a', name: 'Plain Rice',                            serving: '' },
    { cat: '6b', name: '',                                      serving: '' },
    { cat: 7,    name: 'Bhel Salad',                            serving: '' },
    { cat: 8,    name: 'Uncut Whole Fruit',                      serving: '' },
    { cat: 9,    name: 'Fresh Fruit Juice',                      serving: '' },
  ]},
  { id: 'n9', title: 'Night 9 — Dinner', sub: 'Muharram 9', items: [
    { cat: 1,    name: 'Salt',                                  serving: '' },
    { cat: 2,    name: 'Red Lentil Halwa',                      serving: '' },
    { cat: 3,    name: 'Veg Pasta',                             serving: '' },
    { cat: 4,    name: '',                                      serving: '' },
    { cat: 5,    name: 'Roti / Garlic Bread / Naan',            serving: '' },
    { cat: '6a', name: 'Sticky Rice (Beetha Chawal)',            serving: '' },
    { cat: '6b', name: 'Coconut Meat Gravy',                    serving: 'Serve with Rice' },
    { cat: 7,    name: 'Carrot Salad with Vinegar',             serving: '' },
    { cat: 8,    name: 'Uncut Whole Fruit',                      serving: '' },
    { cat: 9,    name: 'Fresh Fruit Juice',                      serving: '' },
  ]},
  { id: 'd9', title: 'Day 9 — Lunch', sub: 'Muharram 9', items: [
    { cat: 1,    name: 'Salt',                                  serving: '' },
    { cat: 2,    name: 'Ice Cream',                             serving: '' },
    { cat: 3,    name: 'Ragza Pens (Spiced Chickpea Pancake)',  serving: '' },
    { cat: 4,    name: '',                                      serving: '' },
    { cat: 5,    name: '',                                      serving: '' },
    { cat: '6a', name: 'Hasha with Meat',                       serving: '' },
    { cat: '6b', name: '',                                      serving: '' },
    { cat: 7,    name: 'Yogurt with Cereal / Cornflakes',       serving: '' },
    { cat: 8,    name: 'Uncut Whole Fruit',                      serving: '' },
    { cat: 9,    name: 'Honey Water',                           serving: '' },
  ]},
  { id: 'na', title: 'Night of Ashura — Dinner', sub: 'Muharram 10', items: [
    { cat: 1,    name: 'Salt',                                  serving: '' },
    { cat: 2,    name: 'Ice Cream',                             serving: '' },
    { cat: 3,    name: 'Salted Meat Pieces (Namkeen Gosht)',    serving: '' },
    { cat: 4,    name: '',                                      serving: '' },
    { cat: 5,    name: 'Roti / Manda / Naan',                   serving: '' },
    { cat: '6a', name: 'Plain Rice',                            serving: '' },
    { cat: '6b', name: 'Whole Red Lentil Dal',                  serving: 'Serve with Rice' },
    { cat: 7,    name: 'Spiced Potatoes (Masala Bateta)',       serving: '' },
    { cat: 8,    name: 'Uncut Whole Fruit',                      serving: '' },
    { cat: 9,    name: 'Fresh Fruit Juice',                      serving: '' },
  ]},
  { id: 'da', title: 'Day of Ashura — Lunch', sub: 'Muharram 10', items: [
    { cat: 1,    name: 'Salt',                                  serving: '' },
    { cat: 2,    name: 'Semolina Halwa with Charoli',           serving: '' },
    { cat: 3,    name: '',                                      serving: '' },
    { cat: 4,    name: 'Haji (Spiced Minced Meat)',             serving: 'Serve with Roti' },
    { cat: 5,    name: 'Roti / Manda / Naan',                   serving: '' },
    { cat: '6a', name: 'Khichdi',                               serving: '' },
    { cat: '6b', name: 'Kadhi (Optional)',                       serving: 'Serve with Khichdi' },
    { cat: 7,    name: '',                                      serving: '' },
    { cat: 8,    name: 'Uncut Whole Fruit',                      serving: '' },
    { cat: 9,    name: 'Yogurt (Packed)',                       serving: '' },
  ]},
  { id: 'd12', title: '12th — Lunch', sub: 'Muharram 12', items: [
    { cat: 1,    name: 'Salt',                                  serving: '' },
    { cat: 2,    name: 'Halwa (Sweet Pudding)',                  serving: '' },
    { cat: 3,    name: 'Local Kharas (Vegetable or Meat)',      serving: '' },
    { cat: 4,    name: '',                                      serving: '' },
    { cat: 5,    name: 'Roti / Manda / Naan',                   serving: '' },
    { cat: '6a', name: 'Plain Rice',                            serving: '' },
    { cat: '6b', name: 'Dal Gosht (Lentil Meat Gravy)',         serving: 'Serve with Rice' },
    { cat: 7,    name: 'Pickle (Achar)',                        serving: '' },
    { cat: 8,    name: 'Uncut Whole Fruit',                      serving: '' },
    { cat: 9,    name: 'Juice / Sharbat',                       serving: '' },
  ]},
];
